In [82]:
import pandas as pd
import matplotlib
import sys
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [83]:
df_mfo = pd.read_excel('./1. mfo for ML.xlsx', header=0, skiprows=[1])

In [84]:
df_mfo.head(2)

,Полное наименование,Сокращенное наименование,ОГРН,Дата включения в реестр,ПНП,Субъект,Адрес сайта в реестре,Найденный бренд в сервисах по данной организации,"Ключевые параметры, по которым определена принадлежность бренда к организации",Количество сработавших ключевых параметров,...,Количество упоминаний бренда,"Доля упоминаний бренда, найденных в обоих сервисах",Найденные сайты по бренду,Коэффициент совпадения сайтов,Результаты сравнений с сайтом,Обратная связь от ПНП,Примечание,Согласие с ПНП,Примечание АЦ,Конечное
0,Общество с ограниченной ответственностью микро...,ООО МКК «Равенство»,1211800011906,08.09.2021,Волго-Вятское главное управление Центрального ...,Удмуртская Республика,https://soyuzdengi.ru,Союзденьги,сайт (полное совпадение); частота упоминаний,2,...,52,52.0,dengidozp.ru; союзденьги.рф; soyuzdengi.ru; ht...,100,soyuzdengi.ru: soyuzdengi.ru (100); союзденьги...,бренд определен верно,Подтверждается отчетом визуального контроля,NaN,NaN,да
1,Общество с ограниченной ответственностью микро...,ООО МКК «Равенство»,1211800011906,08.09.2021,Волго-Вятское главное управление Центрального ...,Удмуртская Республика,https://soyuzdengi.ru,Динар,сайт (полное совпадение),1,...,12,12.0,https://soyuzdengi.ru/; dengidozp.ru,100,soyuzdengi.ru: soyuzdengi.ru (100); dengidozp....,бренд определен неверно,Верный бренд - Союзденьги,ВВГУ,Верный бренд - Союзденьги. Динар встречается р...,нет

In [85]:
df_ps = pd.read_excel('./2. ps for ML.xlsx', header=0, skiprows=[1])

In [86]:
df_ps.head(2)

,Полное наименование,Сокращенное наименование,ОГРН,Дата включения в реестр,ПНП,Субъект,Адрес сайта в реестре,Найденный бренд в сервисах по данной организации,"Ключевые параметры, по которым определена принадлежность бренда к организации",Количество сработавших ключевых параметров,...,"Доля упоминаний бренда, найденных в обоих сервисах",Unnamed: 20,Найденные сайты по бренду,Коэффициент совпадения сайтов,Результаты сравнений с сайтом,Обратная связь от ПНП,Примечание,Согласие с ПНП,Примечание АЦ,Конечное
0,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЛОМБ...","ООО ""ЛОМБАРД ГРАНТ""",1226300001421,01.04.2022,Волго-Вятское главное управление Центрального ...,Самарская область,NaN,Гарант,наименование (частичное совпадение),1,...,100.0,NaN,NaN,0,NaN,бренд определен неверно,Владелец ломбарда является также владельцем ОО...,NaN,NaN,нет
1,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЛОМБ...","ООО ""ЛОМБАРД ""ОПОРА""",1217300009222,29.10.2021,Волго-Вятское главное управление Центрального ...,Ульяновская область,NaN,Опора,наименование (полное совпадение),1,...,100.0,NaN,https://oporazaim.ru/dimitrovgrad; oporazaim.ru,0,NaN,бренд определен верно,NaN,NaN,бренд определен верно,да

In [87]:
df_mfo = df_mfo.iloc[:,[13,15,16,17,18,19,25]]

In [88]:
df_mfo.head(2)

,Коэффициент совпадения бренда с наименованием,"Количество упоминаний об организациях с указанным видом деятельности, найденных в обоих сервисах",Количество упоминаний бренда,"Доля упоминаний бренда, найденных в обоих сервисах",Найденные сайты по бренду,Коэффициент совпадения сайтов,Конечное
0,38,100,52,52.0,dengidozp.ru; союзденьги.рф; soyuzdengi.ru; ht...,100,да
1,18,100,12,12.0,https://soyuzdengi.ru/; dengidozp.ru,100,нет

In [89]:
df_mfo.shape

(614, 7)

In [90]:
df_ps = df_ps.iloc[:,[14,17,18,19,21,22,28]]

In [91]:
df_ps.head(2)

,Коэффициент совпадения бренда с наименованием,"Количество упоминаний об организациях с указанным видом деятельности, найденных в обоих сервисах",Количество упоминаний бренда,"Доля упоминаний бренда, найденных в обоих сервисах",Найденные сайты по бренду,Коэффициент совпадения сайтов,Конечное
0,91,1,1,100.0,NaN,0,нет
1,100,2,2,100.0,https://oporazaim.ru/dimitrovgrad; oporazaim.ru,0,да

In [92]:
df_mfo_add = pd.read_excel('./4. МФО Clear.xlsx', header=0, skiprows=[1])

In [93]:
df_mfo_add.head(2)

,Полное наименование,Сокращенное наименование,ОГРН,Дата включения в реестр,Адрес сайта в реестре,"Количество упоминаний об организациях с указанным видом деятельности, найденных в обоих сервисах",Найденный бренд в сервисах по данной организации,"Доля упоминаний бренда, найденных в обоих сервисах",Интерпретация бренда в сервисах,Найденные сайты по бренду,"Ключевые параметры, по которым определена принадлежность бренда к организации",Количество сработавших ключевых параметров,Вероятность принадлежности бренда,Количество найденных брендов,Коэффициент совпадения бренда с наименованием,Коэффициент совпадения сайтов,Количество упоминаний бренда,Результаты сравнений с наименованием,Результаты сравнений с сайтом
0,Общество с ограниченной ответственностью Микро...,ООО МКК «Мимоза»,5187746030896,14.02.2019,NaN,2,Бери деньги,100.0,Бери Деньги (1); БериДеньги (1),быстроналичные.рф,бренд не определен,0,0,0,15,0,2,"бери деньги: мимоза (15), mimoza (0); беридень...",NaN
1,Общество с ограниченной ответственностью «Микр...,ООО «Микрокредитная компания Финансовая розница»,5187746030874,14.02.2019,http://finroznica.ru,12,Честноденьги,25.0,ЧестноДеньги (1); Честно деньги (1); Честноден...,NaN,бренд не определен,0,0,0,32,0,3,"честноденьги: финансовая розница (27), finanso...",NaN

In [94]:
df_mfo_add = df_mfo_add.iloc[:,[14,5,16,7,9,15]]

In [95]:
df_mfo_add.head(2)

,Коэффициент совпадения бренда с наименованием,"Количество упоминаний об организациях с указанным видом деятельности, найденных в обоих сервисах",Количество упоминаний бренда,"Доля упоминаний бренда, найденных в обоих сервисах",Найденные сайты по бренду,Коэффициент совпадения сайтов
0,15,2,2,100.0,быстроналичные.рф,0
1,32,12,3,25.0,NaN,0

In [96]:
df_ps_add = pd.read_excel('./3. Ломбарды Clear.xlsx', header=0, skiprows=[1])

In [97]:
df_ps_add.head(2)

,Полное наименование,Сокращенное наименование,ОГРН,Дата включения в реестр,Адрес сайта в реестре,"Количество упоминаний об организациях с указанным видом деятельности, найденных в обоих сервисах",Найденный бренд в сервисах по данной организации,"Доля упоминаний бренда, найденных в обоих сервисах",Интерпретация бренда в сервисах,Найденные сайты по бренду,"Ключевые параметры, по которым определена принадлежность бренда к организации",Количество сработавших ключевых параметров,Вероятность принадлежности бренда,Количество найденных брендов,Коэффициент совпадения бренда с наименованием,Коэффициент совпадения сайтов,Количество упоминаний бренда,Результаты сравнений с наименованием,Результаты сравнений с сайтом
0,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЛОМБ...","ООО ""Ломбард Ваш Успех""",5187746026650,26.12.2018,NaN,4,Благо кредит,25.0,Благо кредит (1),lombardblago.ru,бренд определен по другой строке,0,0,1,29,0,1,"благо кредит: vash uspeh (9), ваш успех (29)",NaN
1,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""ЛОМБ...","ООО ""Ломбард Ваш Успех""",5187746026650,26.12.2018,NaN,4,Cash 4 gold,25.0,Cash 4 gold (1),gold500.ru,бренд определен по другой строке,0,0,1,38,0,1,"cash 4 gold: vash uspeh (38), ваш успех (10)",NaN

In [98]:
df_ps_add = df_ps_add.iloc[:,[14,5,16,7,9,15]]

In [99]:
df_ps_add.head(2)

,Коэффициент совпадения бренда с наименованием,"Количество упоминаний об организациях с указанным видом деятельности, найденных в обоих сервисах",Количество упоминаний бренда,"Доля упоминаний бренда, найденных в обоих сервисах",Найденные сайты по бренду,Коэффициент совпадения сайтов
0,29,4,1,25.0,lombardblago.ru,0
1,38,4,1,25.0,gold500.ru,0

In [100]:
new_column_names = [
    'name_match', 'mentioning_type', 'mentioning_brand', 'share_of_mentions','sites','site_match','affiliation']

In [101]:
df_mfo_add['affiliation'] = 0
df_ps_add['affiliation'] = 0

In [102]:
df_mfo.columns = new_column_names
df_ps.columns = new_column_names
df_mfo_add.columns = new_column_names
df_ps_add.columns = new_column_names

In [103]:
df = pd.concat([df_mfo, df_ps, df_mfo_add, df_ps_add])

In [104]:
df.head()

,name_match,mentioning_type,mentioning_brand,share_of_mentions,sites,site_match,affiliation
0,38,100,52,52.0,dengidozp.ru; союзденьги.рф; soyuzdengi.ru; ht...,100,да
1,18,100,12,12.0,https://soyuzdengi.ru/; dengidozp.ru,100,нет
2,100,100,1,1.0,https://soyuzdengi.ru/,100,да
3,100,3,1,33.3,https://vsegdazaem.ru/,100,да
4,31,23,13,56.5,https://dengiaktiv.ru/adresa-ofisov-kamenka/; ...,45,да

In [105]:
condition = df['sites'].isna()
df.loc[condition, 'site_match'] = -999
df = df.drop('sites', axis=1)

In [106]:
df[condition]

,name_match,mentioning_type,mentioning_brand,share_of_mentions,site_match,affiliation
8,100,2,2,100.0,-999,да
12,100,2,2,100.0,-999,да
15,95,6,2,33.3,-999,да
30,100,3,1,33.3,-999,да
32,100,1,1,100.0,-999,да
...,...,...,...,...,...,...
3007,26,1,1,100.0,-999,0
3008,33,10,4,40.0,-999,0
3011,22,4,1,25.0,-999,0
3014,50,3,3,100.0,-999,0
3015,17,3,1,33.3,-999,0

In [107]:
df.shape

(8269, 6)

In [108]:
condition = (df['affiliation'] == "да") | (df['affiliation'] == 1)
df.loc[condition, 'affiliation'] = 1

In [109]:
condition = (df['affiliation'] == "нет") |(df['affiliation'] == 0)
df.loc[condition, 'affiliation'] = 0

In [110]:
df.describe()

,name_match,mentioning_type,mentioning_brand,share_of_mentions,site_match
count,8269.000000,8269.000000,8269.000000,8269.000000,8269.000000
mean,38.677228,166.822107,3.879792,19.257105,-289.515782
std,27.997113,310.244000,22.979410,28.682306,487.469989
min,0.000000,1.000000,1.000000,0.100000,-999.000000
25%,22.000000,8.000000,1.000000,1.200000,-999.000000
50%,30.000000,34.000000,1.000000,5.100000,8.000000
75%,45.000000,151.000000,2.000000,25.000000,54.000000
max,100.000000,1863.000000,1370.000000,100.000000,100.000000

In [111]:
df.isna().sum()

name_match           0
mentioning_type      0
mentioning_brand     0
share_of_mentions    0
site_match           0
affiliation          0
dtype: int64

In [112]:
df

,name_match,mentioning_type,mentioning_brand,share_of_mentions,site_match,affiliation
0,38,100,52,52.0,100,1
1,18,100,12,12.0,100,0
2,100,100,1,1.0,100,1
3,100,3,1,33.3,100,1
4,31,23,13,56.5,45,1
...,...,...,...,...,...,...
3011,22,4,1,25.0,-999,0
3012,0,12,1,8.3,10,0
3013,0,14,1,7.1,0,0
3014,50,3,3,100.0,-999,0
3015,17,3,1,33.3,-999,0

In [113]:
df.dtypes

name_match             int64
mentioning_type        int64
mentioning_brand       int64
share_of_mentions    float64
site_match             int64
affiliation           object
dtype: object

In [114]:
df['affiliation'] = df['affiliation'].astype(bool)

## RandomForest

In [115]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [116]:
X = df.drop('affiliation', axis=1)
y = df['affiliation']

In [117]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [118]:
rf_classifier = RandomForestClassifier(
    n_estimators=100, 
    random_state=42) 
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [119]:
y_pred = rf_classifier.predict(X_test)

In [120]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred)

# Precision
precision = precision_score(y_test, y_pred)

# Recall
recall = recall_score(y_test, y_pred)

# F1 Score
f1 = f1_score(y_test, y_pred)

# ROC-AUC Score
roc_auc = roc_auc_score(y_test, rf_classifier.predict_proba(X_test)[:, 1])

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC-AUC Score:", roc_auc)

Accuracy: 0.9766223297057638
Precision: 0.9046321525885559
Recall: 0.9352112676056338
F1 Score: 0.9196675900277008
ROC-AUC Score: 0.9950280232665987

In [121]:
feature_importances = rf_classifier.feature_importances_
column_names = X.columns
feature_importance_dict = dict(zip(column_names, feature_importances))
feature_importance_dict

{'name_match': 0.5510838881693922,
 'mentioning_type': 0.05654313485131766,
 'mentioning_brand': 0.039124310713722125,
 'share_of_mentions': 0.1880396534175054,
 'site_match': 0.16520901284806264}

## Voting

In [167]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

X = df.drop('affiliation', axis=1)
y = df['affiliation']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)


clf1 = LogisticRegression(random_state=42)
clf2 = DecisionTreeClassifier(random_state=42)
clf3 = SVC(probability=True, random_state=42)

voting_clf = VotingClassifier(estimators=[('lr', clf1), ('dt', clf2), ('svc', clf3)], voting='soft')
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=42)),
                             ('dt', DecisionTreeClassifier(random_state=42)),
                             ('svc', SVC(probability=True, random_state=42))],
                 voting='soft')

In [168]:
y_pred = voting_clf.predict(X_test)

In [169]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred)

# Precision
precision = precision_score(y_test, y_pred)

# Recall
recall = recall_score(y_test, y_pred)

# F1 Score
f1 = f1_score(y_test, y_pred)

# ROC-AUC Score
roc_auc = roc_auc_score(y_test, voting_clf.predict_proba(X_test)[:, 1])

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC-AUC Score:", roc_auc)

Accuracy: 0.9685610640870617
Precision: 0.9085545722713865
Recall: 0.8676056338028169
F1 Score: 0.887608069164265
ROC-AUC Score: 0.9920183376836751

## XGBoost

In [170]:
import xgboost as xgb
from sklearn.model_selection import train_test_split

X = df.drop('affiliation', axis=1)
y = df['affiliation']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [171]:
model = xgb.XGBClassifier(objective='multi:softmax', num_class=3, random_state=42)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=3,
              num_parallel_tree=None, ...)

In [172]:
y_pred = model.predict(X_test)

In [173]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred)

# Precision
precision = precision_score(y_test, y_pred)

# Recall
recall = recall_score(y_test, y_pred)

# F1 Score
f1 = f1_score(y_test, y_pred)

# ROC-AUC Score
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC-AUC Score:", roc_auc)

Accuracy: 0.9742039500201531
Precision: 0.907563025210084
Recall: 0.9126760563380282
F1 Score: 0.9101123595505617
ROC-AUC Score: 0.9947689902349184

In [129]:
feature_importances = model.feature_importances_
column_names = X.columns
feature_importance_dict = dict(zip(column_names, feature_importances))
feature_importance_dict

{'name_match': 0.63561255,
 'mentioning_type': 0.03392888,
 'mentioning_brand': 0.0486594,
 'share_of_mentions': 0.046185486,
 'site_match': 0.23561366}

## CatBoost

In [174]:
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split

X = df.drop('affiliation', axis=1)
y = df['affiliation']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [175]:
model = CatBoostClassifier(iterations=100, depth=6, learning_rate=0.1, loss_function='MultiClass', random_state=42)
model.fit(X_train, y_train, verbose=False)

In [176]:
y_pred = model.predict(X_test)

In [177]:
mask = y_pred == "False"
y_pred[mask] = False
mask = y_pred == "True"
y_pred[mask] = True
y_pred = pd.Series(y_pred.flatten())

In [178]:
y_pred = y_pred.astype(bool)
y_pred

0       False
1        True
2       False
3       False
4       False
        ...
2476    False
2477     True
2478    False
2479    False
2480    False
Length: 2481, dtype: bool

In [179]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred)

# Precision
precision = precision_score(y_test, y_pred)

# Recall
recall = recall_score(y_test, y_pred)

# F1 Score
f1 = f1_score(y_test, y_pred)

# ROC-AUC Score
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC-AUC Score:", roc_auc)

Accuracy: 0.9798468359532446
Precision: 0.9045092838196287
Recall: 0.9605633802816902
F1 Score: 0.9316939890710383
ROC-AUC Score: 0.9956567249214952

In [166]:
feature_importances = model.feature_importances_
column_names = X.columns
feature_importance_dict = dict(zip(column_names, feature_importances))
feature_importance_dict

{'name_match': 56.07189765134811,
 'mentioning_type': 6.746482817645194,
 'mentioning_brand': 5.226888435499349,
 'share_of_mentions': 11.188065021450196,
 'site_match': 20.766666074057138}